# Generated by Django 5.0.1 on 2024-01-22 15:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_card_id', models.TextField()),
                ('cash_left', models.FloatField()),
                ('used', models.BooleanField()),
            ],
        ),                         
        migrations.CreateModel(
            name='OpenDrop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('website_id', models.IntegerField()),
                ('title', models.TextField()),
                ('end_datetime', models.DateField(default=datetime.datetime(2024, 1, 22, 16, 7, 32, 21486))),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingDrop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('website_id', models.IntegerField()),
                ('title', models.TextField()),
                ('open_datetime', models.DateTimeField(default=datetime.datetime(2024, 1, 22, 16, 7, 32, 21486))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('registration_datetime', models.DateTimeField(default=datetime.datetime(2024, 1, 22, 16, 7, 32, 3535))),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bought_datetime', models.DateTimeField(default=datetime.datetime(2024, 1, 22, 16, 7, 32, 20489))),
                ('shipped_datetime', models.DateTimeField(default=datetime.datetime(2024, 1, 22, 16, 7, 32, 20489))),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_name', models.TextField()),
                ('success', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Logout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('success', models.BooleanField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 1, 22, 16, 7, 32, 21486))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('success', models.BooleanField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 1, 22, 16, 7, 32, 21486))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
    