# Generated by Django 5.0.1 on 2024-02-05 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bought_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 53, 26, 33131)),
        ),
        migrations.AlterField(
            model_name='item',
            name='shipped_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 53, 26, 33131)),
        ),
        migrations.AlterField(
            model_name='login',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 53, 26, 33131)),
        ),
        migrations.AlterField(
            model_name='logout',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 53, 26, 33131)),
        ),
        migrations.AlterField(
            model_name='opendrop',
            name='end_datetime',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 9, 53, 26, 34128)),
        ),
        migrations.AlterField(
            model_name='upcomingdrop',
            name='open_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 53, 26, 33131)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 53, 26, 16176)),
        ),
    ]
