# Generated by Django 5.0.1 on 2024-02-05 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_item_bought_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bought_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 55, 56, 155734)),
        ),
        migrations.AlterField(
            model_name='item',
            name='shipped_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 55, 56, 155734)),
        ),
        migrations.AlterField(
            model_name='login',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 55, 56, 155734)),
        ),
        migrations.AlterField(
            model_name='logout',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 55, 56, 156732)),
        ),
        migrations.AlterField(
            model_name='opendrop',
            name='end_datetime',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 9, 55, 56, 156732)),
        ),
        migrations.AlterField(
            model_name='upcomingdrop',
            name='open_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 55, 56, 156732)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 55, 56, 138780)),
        ),
    ]
