# Generated by Django 5.0.1 on 2024-02-05 09:28

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_login_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 10, 28, 25, 990418)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_name',
            field=models.CharField(),
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='LogoutInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
