# Generated by Django 5.0.1 on 2024-02-05 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_creditcard_credit_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 10, 30, 29, 241869)),
        ),
    ]
