# Generated by Django 5.0.1 on 2024-02-05 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_login_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 10, 32, 19, 576856)),
        ),
    ]
