# Generated by Django 5.0.1 on 2024-02-05 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_login_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoutinfo',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='login',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 10, 35, 52, 641166)),
        ),
        migrations.DeleteModel(
            name='LoginInfo',
        ),
        migrations.DeleteModel(
            name='LogoutInfo',
        ),
    ]
