# Generated by Django 5.0.1 on 2024-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField()),
                ('password', models.CharField()),
                ('email', models.CharField()),
                ('registration_datetime', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
