# Generated by Django 5.0.1 on 2024-02-05 11:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_card_id', models.CharField()),
                ('cash_left', models.FloatField()),
                ('used', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenDrop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('website_id', models.IntegerField()),
                ('title', models.CharField()),
                ('end_datetime', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingDrop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('website_id', models.IntegerField()),
                ('title', models.CharField()),
                ('open_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField()),
                ('password', models.CharField()),
                ('email', models.CharField()),
                ('registration_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bought_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipped_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_name', models.CharField()),
                ('success', models.BooleanField()),
                ('user_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='controller.user')),
            ],
        ),
        migrations.CreateModel(
            name='Logout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('success', models.BooleanField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.user')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('success', models.BooleanField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.user')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.user'),
        ),
    ]
